<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:ns0="http://TargetNamespace.com/OCCStockUpdate_updateInventory_request" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Resources/nxsd_updateInventoryReq.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://TargetNamespace.com/OCCStockUpdate_updateInventory_request"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Resources/nxsd_updateInventoryReq.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://TargetNamespace.com/OCCStockUpdate_updateInventory_request"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED FEB 28 14:40:39 BRT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:Root-Element>
         <ns0:preorderThreshold>
            <xsl:value-of select="/ns0:Root-Element/ns0:preorderThreshold"/>
         </ns0:preorderThreshold>
         <ns0:backorderLevel>
            <xsl:value-of select="/ns0:Root-Element/ns0:backorderLevel"/>
         </ns0:backorderLevel>
         <ns0:preorderLevel>
            <xsl:value-of select="/ns0:Root-Element/ns0:preorderLevel"/>
         </ns0:preorderLevel>
         <ns0:locationId>
            <xsl:value-of select="/ns0:Root-Element/ns0:locationId"/>
         </ns0:locationId>
         <ns0:availabilityDate>
            <xsl:value-of select="/ns0:Root-Element/ns0:availabilityDate"/>
         </ns0:availabilityDate>
         <ns0:backorderThreshold>
            <xsl:value-of select="/ns0:Root-Element/ns0:backorderThreshold"/>
         </ns0:backorderThreshold>
         <ns0:stockThreshold>
            <xsl:value-of select="/ns0:Root-Element/ns0:stockThreshold"/>
         </ns0:stockThreshold>
         <ns0:type>
            <xsl:value-of select="/ns0:Root-Element/ns0:type"/>
         </ns0:type>
         <ns0:stockLevel>
            <xsl:value-of select="/ns0:Root-Element/ns0:stockLevel"/>
         </ns0:stockLevel>
      </ns0:Root-Element>
   </xsl:template>
</xsl:stylesheet>