<wsdl:definitions name="ForgotPassword" targetNamespace="http://xmlns.oracle.com/SBAplPassarela/PASSSBForgotPassword/ForgotPassword" xmlns:tns="http://xmlns.oracle.com/SBAplPassarela/PASSSBForgotPassword/ForgotPassword" xmlns:inp1="http://TargetNamespace.com/ForgotPassword_queryProfileAll_request" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <plnk:partnerLinkType name="ForgotPassword">
    <plnk:role name="ForgotPasswordProvider" portType="tns:ForgotPassword_ptt"/>
  </plnk:partnerLinkType>
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://TargetNamespace.com/ForgotPassword_queryProfileAll_request" schemaLocation="nxsd_interfaceProdileReq.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="queryProfileAll_inputMessage">
    <wsdl:part name="request" element="inp1:Root-Element"/>
  </wsdl:message>
  <wsdl:message name="queryProfileAll_outputMessage">
    <wsdl:part name="reply" element="inp1:Root-Element"/>
  </wsdl:message>
  <wsdl:portType name="ForgotPassword_ptt">
    <wsdl:operation name="queryProfileAll">
      <wsdl:input message="tns:queryProfileAll_inputMessage"/>
      <wsdl:output message="tns:queryProfileAll_outputMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ForgotPassword_ptt-binding" type="tns:ForgotPassword_ptt">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="queryProfileAll">
      <soap:operation soapAction="queryProfileAll"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>