<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:ns0="http://TargetNamespace.com/ERPPassarelaCreditBalance_paymentBalance_response" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://TargetNamespace.com/PaymentCreditBalancePS_payment_credit_response" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://TargetNamespace.com/PaymentCreditBalancePS_payment_credit_request" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 ns1 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Resources/nxsd_PaymentBalanceRes.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://TargetNamespace.com/ERPPassarelaCreditBalance_paymentBalance_response"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Resources/nxsd_PaymentCreditStoreReq.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://TargetNamespace.com/PaymentCreditBalancePS_payment_credit_request"/>
            <oracle-xsl-mapper:param name="request"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Resources/nxsd_PaymentCreditStoreRes.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://TargetNamespace.com/PaymentCreditBalancePS_payment_credit_response"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON MAR 19 11:31:06 BRT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="currentTimestamp"/>
   <xsl:param name="request"/>
   <xsl:template match="/">
      <tns:Root-Element>
         <tns:amount>
            <xsl:value-of select="$request/ns1:Root-Element/ns1:amount"/>
         </tns:amount>
         <tns:orderId>
            <xsl:value-of select="$request/ns1:Root-Element/ns1:orderId"/>
         </tns:orderId>
         <tns:channel>
            <xsl:value-of select="$request/ns1:Root-Element/ns1:channel"/>
         </tns:channel>
         <tns:authorizationResponse>
            <tns:hostTransactionTimestamp>
               <xsl:value-of select="$currentTimestamp"/>
            </tns:hostTransactionTimestamp>
            <tns:responseReason>authResponseReason</tns:responseReason>
            <tns:responseDescription>
               <xsl:value-of select="/ns0:Root-Element/ns0:message"/>
            </tns:responseDescription>
            <tns:merchantTransactionId>
               <xsl:value-of select="$request/ns1:Root-Element/ns1:transactionId"/>
            </tns:merchantTransactionId>
            <tns:hostTransactionId>
               <xsl:value-of select="$request/ns1:Root-Element/ns1:transactionId"/>
            </tns:hostTransactionId>
            <tns:responseCode>1000</tns:responseCode>
            <tns:merchantTransactionTimestamp>
               <xsl:value-of select="$currentTimestamp"/>
            </tns:merchantTransactionTimestamp>
         </tns:authorizationResponse>
         <tns:locale>
            <xsl:value-of select="$request/ns1:Root-Element/ns1:locale"/>
         </tns:locale>
         <tns:transactionId>
            <xsl:value-of select="$request/ns1:Root-Element/ns1:transactionId"/>
         </tns:transactionId>
         <tns:transactionTimestamp>
            <xsl:value-of select="$request/ns1:Root-Element/ns1:transactionTimestamp"/>
         </tns:transactionTimestamp>
         <tns:transactionType>
            <xsl:value-of select="$request/ns1:Root-Element/ns1:transactionType"/>
         </tns:transactionType>
         <tns:paymentId>
            <xsl:value-of select="$request/ns1:Root-Element/ns1:paymentId"/>
         </tns:paymentId>
         <tns:paymentMethod>
            <xsl:value-of select="$request/ns1:Root-Element/ns1:paymentMethod"/>
         </tns:paymentMethod>
         <tns:siteId>
            <xsl:value-of select="$request/ns1:Root-Element/ns1:siteId"/>
         </tns:siteId>
         <tns:currencyCode>
            <xsl:value-of select="$request/ns1:Root-Element/ns1:currencyCode"/>
         </tns:currencyCode>
         <tns:gatewayId>
            <xsl:value-of select="$request/ns1:Root-Element/ns1:gatewayId"/>
         </tns:gatewayId>
      </tns:Root-Element>
   </xsl:template>
</xsl:stylesheet>
