<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ResponsysUpdateShopperPS"
     targetNamespace="http://xmlns.oracle.com/SBAplPassarela/PASSSBUpdateShopper/ResponsysUpdateShopperPS"
     xmlns:tns="http://xmlns.oracle.com/SBAplPassarela/PASSSBUpdateShopper/ResponsysUpdateShopperPS"
     xmlns:inp1="http://TargetNamespace.com/ResponsysUpdateShopperPS_profile_request"
     xmlns:inp2="http://TargetNamespace.com/ResponsysUpdateShopperPS_profile_response"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ResponsysUpdateShopperPS">
        <plnk:role name="ResponsysUpdateShopperPSProvider" portType="tns:ResponsysUpdateShopperPS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://TargetNamespace.com/ResponsysUpdateShopperPS_profile_request"
                 schemaLocation="nxsd_ProfileReq.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://TargetNamespace.com/ResponsysUpdateShopperPS_profile_response"
                 schemaLocation="nxsd_ProfileRes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="profile_inputMessage">
        <wsdl:part name="request" element="inp1:Root-Element"/>
    </wsdl:message>
    <wsdl:message name="profile_outputMessage">
        <wsdl:part name="reply" element="inp2:Root-Element"/>
    </wsdl:message>
    <wsdl:portType name="ResponsysUpdateShopperPS_ptt">
        <wsdl:operation name="profile">
            <wsdl:input message="tns:profile_inputMessage"/>
            <wsdl:output message="tns:profile_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
