<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="UpdateShopperPS"
     targetNamespace="http://xmlns.oracle.com/SBAplPassarela/PASSSBUpdateShopper/UpdateShopperPS"
     xmlns:tns="http://xmlns.oracle.com/SBAplPassarela/PASSSBUpdateShopper/UpdateShopperPS"
     xmlns:inp1="http://TargetNamespace.com/ResponsysUpdateShopperPS_profile_request"
     xmlns:inp2="http://TargetNamespace.com/ResponsysUpdateShopperPS_profile_response"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="UpdateShopperPS">
        <plnk:role name="UpdateShopperPSProvider" portType="tns:UpdateShopperPS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://TargetNamespace.com/ResponsysUpdateShopperPS_profile_request"
                 schemaLocation="../v1/Resources/nxsd_ProfileReq.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://TargetNamespace.com/ResponsysUpdateShopperPS_profile_response"
                 schemaLocation="../v1/Resources/nxsd_ProfileRes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="update_shopper_inputMessage">
        <wsdl:part name="request" element="inp1:Root-Element"/>
    </wsdl:message>
    <wsdl:message name="update_shopper_outputMessage">
        <wsdl:part name="reply" element="inp2:Root-Element"/>
    </wsdl:message>
    <wsdl:portType name="UpdateShopperPS_ptt">
        <wsdl:operation name="update_shopper">
            <wsdl:input message="tns:update_shopper_inputMessage"/>
            <wsdl:output message="tns:update_shopper_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
