<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:ns0="http://TargetNamespace.com/AdyenPaymentGateway_authoriseGeneric_response"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:tns="http://TargetNamespace.com/AdyenPaymentGateway_authorise_int_response"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:ns1="http://TargetNamespace.com/AdyenPaymentGateway_authorise_int_request"
                xmlns:ns2="http://TargetNamespace.com/AdyenPaymentGateway_authorise_int_response">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="XSD">
                <oracle-xsl-mapper:schema location="../Resources/Generic/nxsd_authorisePaymentResp.xsd"/>
                <oracle-xsl-mapper:rootElement name="Root-Element"
                                               namespace="http://TargetNamespace.com/AdyenPaymentGateway_authoriseGeneric_response"/>
            </oracle-xsl-mapper:source>
            <oracle-xsl-mapper:source type="XSD">
                <oracle-xsl-mapper:schema location="../Resources/Generic/nxsd_InterfaceAuthorisePaymentReq.xsd"/>
                <oracle-xsl-mapper:rootElement name="Root-Element"
                                               namespace="http://TargetNamespace.com/AdyenPaymentGateway_authorise_int_request"/>
                <oracle-xsl-mapper:param name="bodyRequest"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="XSD">
                <oracle-xsl-mapper:schema location="../Resources/Generic/nxsd_InterfaceAuthorisePaymentRes.xsd"/>
                <oracle-xsl-mapper:rootElement name="Root-Element"
                                               namespace="http://TargetNamespace.com/AdyenPaymentGateway_authorise_int_response"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED FEB 21 13:27:33 BRT 2018].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:param name="bodyRequest"/>
    <xsl:template match="/">
        <tns:Root-Element>
         
            <xsl:if test="$bodyRequest/ns1:Root-Element/ns1:orderId">
                <tns:orderId>
                    <xsl:value-of select="$bodyRequest/ns1:Root-Element/ns1:orderId"/>
                </tns:orderId>
            </xsl:if>
            <xsl:if test="$bodyRequest/ns1:Root-Element/ns1:currencyCode">
                <tns:currencyCode>
                    <xsl:value-of select="$bodyRequest/ns1:Root-Element/ns1:currencyCode"/>
                </tns:currencyCode>
            </xsl:if>
            <xsl:if test="$bodyRequest/ns1:Root-Element/ns1:transactionId">
                <tns:transactionId>
                    <xsl:value-of select="$bodyRequest/ns1:Root-Element/ns1:transactionId"/>
                </tns:transactionId>
            </xsl:if>
            <xsl:if test="$bodyRequest/ns1:Root-Element/ns1:paymentId">
                <tns:paymentId>
                    <xsl:value-of select="$bodyRequest/ns1:Root-Element/ns1:paymentId"/>
                </tns:paymentId>
            </xsl:if>
            <xsl:if test="$bodyRequest/ns1:Root-Element/ns1:amount">
                <tns:amount>
                    <xsl:value-of select="$bodyRequest/ns1:Root-Element/ns1:amount"/>
                </tns:amount>
            </xsl:if>
            <xsl:if test="$bodyRequest/ns1:Root-Element/ns1:transactionType">
                <tns:transactionType>
                    <xsl:value-of select="$bodyRequest/ns1:Root-Element/ns1:transactionType"/>
                </tns:transactionType>
            </xsl:if>
            <ns2:hostTransactionTimestamp>
                <xsl:value-of select="xp20:current-dateTime ( )"/>
            </ns2:hostTransactionTimestamp>
            <xsl:if test="/ns0:Root-Element/ns0:time">
                <tns:transactionTimestamp>
                    <xsl:value-of select="/ns0:Root-Element/ns0:time"/>
                </tns:transactionTimestamp>
            </xsl:if>
            <xsl:if test="$bodyRequest/ns1:Root-Element/ns1:paymentMethod">
                <tns:paymentMethod>
                    <xsl:value-of select="$bodyRequest/ns1:Root-Element/ns1:paymentMethod"/>
                </tns:paymentMethod>
            </xsl:if>
            <xsl:if test="$bodyRequest/ns1:Root-Element/ns1:gatewayId">
                <tns:gatewayId>
                    <xsl:value-of select="$bodyRequest/ns1:Root-Element/ns1:gatewayId"/>
                </tns:gatewayId>
            </xsl:if>
            <xsl:if test="$bodyRequest/ns1:Root-Element/ns1:siteId">
                <tns:siteId>
                    <xsl:value-of select="$bodyRequest/ns1:Root-Element/ns1:siteId"/>
                </tns:siteId>
            </xsl:if>
         
                <xsl:if test="/ns0:Root-Element/ns0:pspReference">
                    <tns:authorizationResponse>
                        <xsl:if test="/ns0:Root-Element/ns0:resultCode">
                            <tns:responseCode>
                                <xsl:value-of select="/ns0:Root-Element/ns0:resultCode"/>
                            </tns:responseCode>
                        </xsl:if>
                        <xsl:if test="/ns0:Root-Element/ns0:message">
                            <tns:responseReason>
                                <xsl:value-of select="/ns0:Root-Element/ns0:message"/>
                            </tns:responseReason>
                        </xsl:if>
                        <xsl:if test="/ns0:Root-Element/ns0:pspReference">
                            <ns2:responseDescription>
                                <xsl:value-of select="/ns0:Root-Element/ns0:pspReference"/>
                            </ns2:responseDescription>
                        </xsl:if>
                        <xsl:if test="/ns0:Root-Element/ns0:authCode">
                            <tns:authorizationCode>
                                <xsl:value-of select="/ns0:Root-Element/ns0:authCode"/>
                            </tns:authorizationCode>
                        </xsl:if>
                        <xsl:if test="/ns0:Root-Element/ns0:pspReference">
                            <tns:hostTransactionId>
                                <xsl:value-of select="/ns0:Root-Element/ns0:pspReference"/>
                            </tns:hostTransactionId>
                        </xsl:if>
                    </tns:authorizationResponse>
                </xsl:if>
           
         
                <ns2:additionalProperties>
                    <xsl:if test="/ns0:Root-Element/ns0:md">
                        <ns2:md>
                            <xsl:value-of select="/ns0:Root-Element/ns0:md"/>
                        </ns2:md>
                    </xsl:if>
                    <xsl:if test="/ns0:Root-Element/ns0:paRequest">
                        <ns2:paRequest>
                            <xsl:value-of select="/ns0:Root-Element/ns0:paRequest"/>
                        </ns2:paRequest>
                    </xsl:if>
                    <xsl:if test="/ns0:Root-Element/ns0:issuerUrl">
                        <ns2:issueURL>
                            <xsl:value-of select="/ns0:Root-Element/ns0:issuerUrl"/>
                        </ns2:issueURL>
                    </xsl:if>
                    <xsl:if test="/ns0:Root-Element/ns0:additionalData/ns0:boletobancario.url">
                        <ns2:boletobancario.url>
                            <xsl:value-of select="/ns0:Root-Element/ns0:additionalData/ns0:boletobancario.url"/>
                        </ns2:boletobancario.url>
                    </xsl:if>
                    <xsl:if test="/ns0:Root-Element/ns0:additionalData/ns0:boletobancario.data">
                        <ns2:boletobancario.data>
                            <xsl:value-of select="/ns0:Root-Element/ns0:additionalData/ns0:boletobancario.data"/>
                        </ns2:boletobancario.data>
                    </xsl:if>
                    <xsl:if test="/ns0:Root-Element/ns0:additionalData/ns0:boletobancario.barCodeReference">
                        <ns2:boletobancario.barCodeReference>
                            <xsl:value-of select="/ns0:Root-Element/ns0:additionalData/ns0:boletobancario.barCodeReference"/>
                        </ns2:boletobancario.barCodeReference>
                    </xsl:if>
                    <xsl:if test="/ns0:Root-Element/ns0:additionalData/ns0:boletobancario.expirationDate">
                        <ns2:boletobancario.expirationDate>
                            <xsl:value-of select="/ns0:Root-Element/ns0:additionalData/ns0:boletobancario.expirationDate"/>
                        </ns2:boletobancario.expirationDate>
                    </xsl:if>
                    <xsl:if test="/ns0:Root-Element/ns0:additionalData/ns0:boletobancario.dueDate">
                        <ns2:boletobancario.dueDate>
                            <xsl:value-of select="/ns0:Root-Element/ns0:additionalData/ns0:boletobancario.dueDate"/>
                        </ns2:boletobancario.dueDate>
                    </xsl:if>
                </ns2:additionalProperties>
           
        </tns:Root-Element>
    </xsl:template>
</xsl:stylesheet>
