<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:ns0="http://TargetNamespace.com/AdyenPaymentGateway_authorise_int_request"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:tns="http://TargetNamespace.com/AdyenPaymentGateway_authoriseGeneric_request"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="XSD">
                <oracle-xsl-mapper:schema location="../Resources/Generic/nxsd_InterfaceAuthorisePaymentReq.xsd"/>
                <oracle-xsl-mapper:rootElement name="Root-Element"
                                               namespace="http://TargetNamespace.com/AdyenPaymentGateway_authorise_int_request"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="XSD">
                <oracle-xsl-mapper:schema location="../Resources/Generic/nxsd_authorisePaymentReq.xsd"/>
                <oracle-xsl-mapper:rootElement name="Root-Element"
                                               namespace="http://TargetNamespace.com/AdyenPaymentGateway_authoriseGeneric_request"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED FEB 21 13:12:38 BRT 2018].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:param name="merchantAccount"/>
    <xsl:template match="/">
        <tns:Root-Element>
            <tns:additionalData>
                <xsl:if test="/ns0:Root-Element/ns0:paymentMethod = 'debit'">
                    <tns:executeThreeD>true</tns:executeThreeD>
                </xsl:if>
            </tns:additionalData>
            <tns:amount>
                <tns:currency>
                    <xsl:value-of select="/ns0:Root-Element/ns0:currencyCode"/>
                </tns:currency>
            </tns:amount>
            <tns:reference>
                <xsl:value-of select="/ns0:Root-Element/ns0:transactionId"/>
            </tns:reference>
            <tns:shopperEmail>
                <xsl:value-of select="/ns0:Root-Element/ns0:billingAddress/ns0:email"/>
            </tns:shopperEmail>
            <tns:shopperReference>
                <xsl:value-of select="concat (/ns0:Root-Element/ns0:billingAddress/ns0:firstName, /ns0:Root-Element/ns0:billingAddress/ns0:lastName )"/>
            </tns:shopperReference>
            <tns:billingAddress>
                <tns:city>
                    <xsl:value-of select="/ns0:Root-Element/ns0:billingAddress/ns0:city"/>
                </tns:city>
                <tns:country>
                    <xsl:value-of select="/ns0:Root-Element/ns0:billingAddress/ns0:country"/>
                </tns:country>
                <tns:postalCode>
                    <xsl:value-of select="/ns0:Root-Element/ns0:billingAddress/ns0:postalCode"/>
                </tns:postalCode>
                <tns:stateOrProvince>
                    <xsl:value-of select="/ns0:Root-Element/ns0:billingAddress/ns0:state"/>
                </tns:stateOrProvince>
                <tns:street>
                    <xsl:value-of select="/ns0:Root-Element/ns0:billingAddress/ns0:address1"/>
                </tns:street>
            </tns:billingAddress>
            <tns:deliveryAddress>
                <tns:city>
                    <xsl:value-of select="/ns0:Root-Element/ns0:shippingAddress/ns0:city"/>
                </tns:city>
                <tns:country>
                    <xsl:value-of select="/ns0:Root-Element/ns0:shippingAddress/ns0:country"/>
                </tns:country>
                <tns:postalCode>
                    <xsl:value-of select="/ns0:Root-Element/ns0:shippingAddress/ns0:postalCode"/>
                </tns:postalCode>
                <tns:stateOrProvince>
                    <xsl:value-of select="/ns0:Root-Element/ns0:shippingAddress/ns0:state"/>
                </tns:stateOrProvince>
                <tns:street>
                    <xsl:value-of select="/ns0:Root-Element/ns0:shippingAddress/ns0:address1"/>
                </tns:street>
            </tns:deliveryAddress>
            <tns:telephoneNumber>
                <xsl:value-of select="/ns0:Root-Element/ns0:billingAddress/ns0:phoneNumber"/>
            </tns:telephoneNumber>
            <tns:shopperName>
                <tns:firstName>
                    <xsl:value-of select="/ns0:Root-Element/ns0:billingAddress/ns0:firstName"/>
                </tns:firstName>
                <tns:lastName>
                    <xsl:value-of select="/ns0:Root-Element/ns0:billingAddress/ns0:lastName"/>
                </tns:lastName>
            </tns:shopperName>
            <tns:md>
                <xsl:value-of select="/ns0:Root-Element/ns0:additionalProperties/ns0:md"/>
            </tns:md>
            <tns:paResponse>
                <xsl:value-of select="/ns0:Root-Element/ns0:additionalProperties/ns0:paResponse"/>
            </tns:paResponse>
            <tns:merchantAccount>
                <xsl:value-of select="$merchantAccount"/>
            </tns:merchantAccount>
        </tns:Root-Element>
    </xsl:template>
</xsl:stylesheet>
