<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:ns1="http://TargetNamespace.com/QueryAccountPS_balance_inquiry_request"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:ns0="http://TargetNamespace.com/ERPPassarelaQueryAccountBalance_query_response"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:tns="http://TargetNamespace.com/QueryAccountPS_balance_inquiry_response"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns1 ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Resources/nxsd_QueryAccountRes.xsd"/>
        <oracle-xsl-mapper:rootElement name="Root-Element"
                                       namespace="http://TargetNamespace.com/ERPPassarelaQueryAccountBalance_query_response"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Resources/nxsd_BalanceInquiryReq.xsd"/>
        <oracle-xsl-mapper:rootElement name="Root-Element"
                                       namespace="http://TargetNamespace.com/QueryAccountPS_balance_inquiry_request"/>
        <oracle-xsl-mapper:param name="BalanceInquiryReq"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Resources/nxsd_BalanceInquiryRes.xsd"/>
        <oracle-xsl-mapper:rootElement name="Root-Element"
                                       namespace="http://TargetNamespace.com/QueryAccountPS_balance_inquiry_response"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED MAR 07 14:48:24 BRT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="BalanceInquiryReq"/>
  <xsl:param name="currentTimestampMiliseconds"/>
  <xsl:template match="/">
    <tns:Root-Element>
      <tns:totalAvailableAmount>200</tns:totalAvailableAmount>
      <tns:transactionType>0600</tns:transactionType>
      <tns:orderId>
        <xsl:value-of select="$BalanceInquiryReq/ns1:Root-Element/ns1:orderId"/>
      </tns:orderId>
      <tns:paymentId>
        <xsl:value-of select="$BalanceInquiryReq/ns1:Root-Element/ns1:paymentId"/>
      </tns:paymentId>
      <tns:channel>
        <xsl:value-of select="$BalanceInquiryReq/ns1:Root-Element/ns1:channel"/>
      </tns:channel>
      <tns:paymentMethod>
        <xsl:value-of select="$BalanceInquiryReq/ns1:Root-Element/ns1:paymentMethod"/>
      </tns:paymentMethod>
      <tns:siteId>
        <xsl:value-of select="$BalanceInquiryReq/ns1:Root-Element/ns1:siteId"/>
      </tns:siteId>
      <tns:locale>
        <xsl:value-of select="$BalanceInquiryReq/ns1:Root-Element/ns1:locale"/>
      </tns:locale>
      <tns:inquireBalanceResponse>
        <tns:hostTransactionTimestamp>
          <xsl:value-of select="$currentTimestampMiliseconds"/>
        </tns:hostTransactionTimestamp>
        <tns:responseReason>inquireBalanceResponseReason</tns:responseReason>
        <tns:storeCredits>
          <tns:storeCreditNumber>
            <xsl:value-of select="$BalanceInquiryReq/ns1:Root-Element/ns1:CPF"/>
          </tns:storeCreditNumber>
          <tns:availableAamount>200</tns:availableAamount>
        </tns:storeCredits>
        <tns:responseDescription>inquireBalanceResponseDescription</tns:responseDescription>
        <tns:merchantTransactionId>
          <xsl:value-of select="$BalanceInquiryReq/ns1:Root-Element/ns1:transactionId"/>
        </tns:merchantTransactionId>
        <tns:hostTransactionId>
          <xsl:value-of select="$BalanceInquiryReq/ns1:Root-Element/ns1:transactionId"/>
        </tns:hostTransactionId>
        <tns:responseCode>5000</tns:responseCode>
        <tns:merchantTransactionTimestamp>
          <xsl:value-of select="$currentTimestampMiliseconds"/>
        </tns:merchantTransactionTimestamp>
      </tns:inquireBalanceResponse>
      <tns:currencyCode>
        <xsl:value-of select="$BalanceInquiryReq/ns1:Root-Element/ns1:currencyCode"/>
      </tns:currencyCode>
      <tns:transactionId>
        <xsl:value-of select="$BalanceInquiryReq/ns1:Root-Element/ns1:transactionId"/>
      </tns:transactionId>
      <tns:transactionTimestamp>
        <xsl:value-of select="$BalanceInquiryReq/ns1:Root-Element/ns1:transactionTimestamp"/>
      </tns:transactionTimestamp>
      <tns:gatewayId>
        <xsl:value-of select="$BalanceInquiryReq/ns1:Root-Element/ns1:gatewayId"/>
      </tns:gatewayId>
    </tns:Root-Element>
  </xsl:template>
</xsl:stylesheet>
