<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://TargetNamespace.com/WebhookOrderSubmitPS_submit_order_request" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:tns="http://TargetNamespace.com/ERPOrderSubmit_orderSumit_request" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Resources/nxsd_submitOrderReq.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://TargetNamespace.com/WebhookOrderSubmitPS_submit_order_request"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Resources/nxsd_orderSubmitERPReq.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://TargetNamespace.com/ERPOrderSubmit_orderSumit_request"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI MAY 11 16:24:34 BRT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:Root-Element>
         <tns:dsDispId>
            <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:id"/>
         </tns:dsDispId>
         <tns:dtOrder>
            <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:submittedDate"/>
         </tns:dtOrder>
         <tns:idSite>
            <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:id"/>
         </tns:idSite>
         <tns:dsSalesChannel>
            <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:salesChannel"/>
         </tns:dsSalesChannel>
         <tns:infoPrice>
            <tns:vlTotalOrder>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:priceInfo/ns0:total"/>
            </tns:vlTotalOrder>
            <tns:vlTotalProduct>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:priceInfo/ns0:amount"/>
            </tns:vlTotalProduct>
            <tns:vlTotalShipCost>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:priceInfo/ns0:shipping"/>
            </tns:vlTotalShipCost>
            <tns:vlOrderDiscount>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:priceInfo/ns0:discountAmount"/>
            </tns:vlOrderDiscount>
         </tns:infoPrice>
         <tns:status>
            <tns:dsStatusOrder>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:state"/>
            </tns:dsStatusOrder>
         </tns:status>
         <xsl:for-each select="/ns0:Root-Element/ns0:order/ns0:paymentGroups">
            <tns:payment>
               <tns:dsFraudResultType>
                  <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:fraudResultType"/>
               </tns:dsFraudResultType>
               <tns:fraudManualReview>
                  <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:fraudManualReview"/>
               </tns:fraudManualReview>
               <tns:authorisationMid>
                  <xsl:value-of select="ns0:id"/>
               </tns:authorisationMid>
               <tns:idPayMethod>
                  <xsl:value-of select="ns0:id"/>
               </tns:idPayMethod>
               <tns:nuParcelsNumber>
                  <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:parcelas"/>
               </tns:nuParcelsNumber>
               <tns:vlValue>
                  <xsl:value-of select="ns0:amount"/>
               </tns:vlValue>
               <tns:transactionId>
                  <xsl:value-of select="ns0:id"/>
               </tns:transactionId>
               <tns:authorizationStatus>
                  <xsl:value-of select="ns0:authorizationStatus/ns0:statusProps/ns0:responseDescription"/>
               </tns:authorizationStatus>
               <tns:boletodueDate>
                  <xsl:value-of select="ns0:authorizationStatus/ns0:statusProps/ns0:boletobancario.dueDate"/>
               </tns:boletodueDate>
               <tns:boletobarCodeReference>
                  <xsl:value-of select="ns0:authorizationStatus/ns0:statusProps/ns0:boletobancario.barCodeReference"/>
               </tns:boletobarCodeReference>
               <tns:boletourl>
                  <xsl:value-of select="ns0:authorizationStatus/ns0:statusProps/ns0:boletobancario.url"/>
               </tns:boletourl>
               <tns:boletoexpirationDate>
                  <xsl:value-of select="ns0:authorizationStatus/ns0:statusProps/ns0:boletobancario.expirationDate"/>
               </tns:boletoexpirationDate>
            </tns:payment>
         </xsl:for-each>
         <tns:shippingInfo>
            <tns:idQuote>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:shippingGroups/ns0:id"/>
            </tns:idQuote>
            <tns:firstname>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:shippingGroups/ns0:shippingAddress/ns0:firstName"/>
            </tns:firstname>
            <tns:lastname>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:shippingGroups/ns0:shippingAddress/ns0:lastName"/>
            </tns:lastname>
            <tns:dsCity>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:shippingGroups/ns0:shippingAddress/ns0:city"/>
            </tns:dsCity>
            <tns:idState>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:shippingGroups/ns0:state"/>
            </tns:idState>
            <tns:idCountry>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:shippingGroups/ns0:id"/>
            </tns:idCountry>
            <tns:idShippingMethod>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:shippingGroups/ns0:shippingMethod"/>
            </tns:idShippingMethod>
            <tns:dsShippingMethod>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:shippingGroups/ns0:shippingMethod"/>
            </tns:dsShippingMethod>
            <tns:dtDeliverySchedule>
               <xsl:value-of select="xp20:current-dateTime ( )"/>
            </tns:dtDeliverySchedule>
            <tns:idPeriodSchedule>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:shippingGroups/ns0:id"/>
            </tns:idPeriodSchedule>
         </tns:shippingInfo>
         <tns:customer>
            <tns:idCustomer>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:profileId"/>
            </tns:idCustomer>
            <tns:dsEmail>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:profile/ns0:email"/>
            </tns:dsEmail>
            <tns:firstName>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:profile/ns0:firstName"/>
            </tns:firstName>
            <tns:lastName>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:profile/ns0:lastName"/>
            </tns:lastName>
            <tns:fgReceiveEmail>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:profile/ns0:email"/>
            </tns:fgReceiveEmail>
            <tns:dsCity>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:profile/ns0:shippingAddress/ns0:city"/>
            </tns:dsCity>
            <tns:idState>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:profile/ns0:shippingAddress/ns0:state"/>
            </tns:idState>
            <tns:idCountry>
               <xsl:value-of select="/ns0:Root-Element/ns0:order/ns0:profile/ns0:shippingAddress/ns0:country"/>
            </tns:idCountry>
         </tns:customer>
      </tns:Root-Element>
   </xsl:template>
</xsl:stylesheet>