<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://passarela.com.br/SubmitOrderRequest" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://passarela.com.br/ErpSubmitReq" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Resources/nxsd_submitOrderRequest.xsd"/>
            <oracle-xsl-mapper:rootElement name="SubmitOrderRequest" namespace="http://passarela.com.br/SubmitOrderRequest"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Resources/nxsd_ErpSubmitReq.xsd"/>
            <oracle-xsl-mapper:rootElement name="ErpSubmitReq" namespace="http://passarela.com.br/ErpSubmitReq"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU APR 19 17:30:03 BRT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ErpSubmitReq>
         <tns:Order>
            <tns:DsDispId>
               <xsl:value-of select="/ns0:SubmitOrderRequest/ns0:order/ns0:id"/>
            </tns:DsDispId>
            <tns:DtOrder>
               <xsl:value-of select="/ns0:SubmitOrderRequest/ns0:order/ns0:submittedDate"/>
            </tns:DtOrder>
            <tns:IdSite>
               <xsl:value-of select="/ns0:SubmitOrderRequest/ns0:order/ns0:siteId"/>
            </tns:IdSite>
            <tns:DsSalesChannel>
               <xsl:value-of select="/ns0:SubmitOrderRequest/ns0:order/ns0:salesChannel"/>
            </tns:DsSalesChannel>
            <tns:Status>
               <tns:DsStatusOrder>
                  <xsl:value-of select="/ns0:SubmitOrderRequest/ns0:order/ns0:state"/>
               </tns:DsStatusOrder>
            </tns:Status>
            <tns:Televendas>
               <tns:IDTelemarketingUser>
                  <xsl:value-of select="/ns0:SubmitOrderRequest/ns0:order/ns0:agentId"/>
               </tns:IDTelemarketingUser>
            </tns:Televendas>
            <tns:Payment>
               <tns:authorisationMid/>
               <tns:IdPayMethod/>
               <tns:TransactionId/>
            </tns:Payment>
         </tns:Order>
      </tns:ErpSubmitReq>
   </xsl:template>
</xsl:stylesheet>
