<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:ns1="http://TargetNamespace.com/OCCGetProfileOrder_profileRequest_response"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:tns="http://TargetNamespace.com/GetEnrichOrderProfile_OrderProfileOCC_response"
                xmlns:ns0="http://TargetNamespace.com/OCCGetProfileOrder_orderRequest_response"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns1 ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../resources/nxsd_OrderRes.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element"
                                           namespace="http://TargetNamespace.com/OCCGetProfileOrder_orderRequest_response"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../resources/nxsd_ProfileRes.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element"
                                           namespace="http://TargetNamespace.com/OCCGetProfileOrder_profileRequest_response"/>
            <oracle-xsl-mapper:param name="profile"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../resources/nxsd_OrderProfileOCCRes.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element"
                                           namespace="http://TargetNamespace.com/GetEnrichOrderProfile_OrderProfileOCC_response"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 08 18:58:27 BRT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="profile"/>
   <xsl:template match="/">
      <tns:Root-Element>
         <tns:lastName>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:lastName"/>
         </tns:lastName>
         <tns:gender>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:gender"/>
         </tns:gender>
         <tns:catalog>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:catalog"/>
         </tns:catalog>
         <tns:roles>
            <tns:function>
               <xsl:value-of select="$profile/ns1:Root-Element/ns1:roles/ns1:function"/>
            </tns:function>
            <tns:relativeTo>
               <tns:id>
                  <xsl:value-of select="$profile/ns1:Root-Element/ns1:roles/ns1:relativeTo/ns1:id"/>
               </tns:id>
            </tns:relativeTo>
            <tns:repositoryId>
               <xsl:value-of select="$profile/ns1:Root-Element/ns1:roles/ns1:repositoryId"/>
            </tns:repositoryId>
         </tns:roles>
         <tns:parentOrganization>
            <tns:name>
               <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:name"/>
            </tns:name>
            <tns:repositoryId>
               <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:repositoryId"/>
            </tns:repositoryId>
            <tns:description>
               <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:description"/>
            </tns:description>
            <tns:active>
               <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:active"/>
            </tns:active>
            <tns:shippingAddress>
               <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:shippingAddress"/>
            </tns:shippingAddress>
            <tns:secondaryAddresses>
               <tns:firstName>
                  <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:secondaryAddresses/ns1:firstName"/>
               </tns:firstName>
               <tns:lastName>
                  <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:secondaryAddresses/ns1:lastName"/>
               </tns:lastName>
               <tns:country>
                  <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:secondaryAddresses/ns1:country"/>
               </tns:country>
               <tns:phoneNumber>
                  <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:secondaryAddresses/ns1:phoneNumber"/>
               </tns:phoneNumber>
               <tns:city>
                  <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:secondaryAddresses/ns1:city"/>
               </tns:city>
               <tns:address2>
                  <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:secondaryAddresses/ns1:address2"/>
               </tns:address2>
               <tns:address1>
                  <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:secondaryAddresses/ns1:address1"/>
               </tns:address1>
               <tns:postalCode>
                  <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:secondaryAddresses/ns1:postalCode"/>
               </tns:postalCode>
               <tns:repositoryId>
                  <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:secondaryAddresses/ns1:repositoryId"/>
               </tns:repositoryId>
               <tns:state>
                  <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:secondaryAddresses/ns1:state"/>
               </tns:state>
            </tns:secondaryAddresses>
            <tns:id>
               <xsl:value-of select="$profile/ns1:Root-Element/ns1:parentOrganization/ns1:id"/>
            </tns:id>
         </tns:parentOrganization>
         <tns:locale>
            <xsl:value-of select="/ns0:Root-Element/ns0:locale"/>
         </tns:locale>
         <tns:profileType>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:profileType"/>
         </tns:profileType>
         <xsl:for-each select="$profile/ns1:Root-Element/ns1:loyaltyPrograms">
            <tns:loyaltyPrograms>
               <tns:programName>
                  <xsl:value-of select="ns1:programName"/>
               </tns:programName>
               <tns:repositoryId>
                  <xsl:value-of select="ns1:repositoryId"/>
               </tns:repositoryId>
               <tns:membershipId>
                  <xsl:value-of select="ns1:membershipId"/>
               </tns:membershipId>
               <tns:programId>
                  <xsl:value-of select="ns1:programId"/>
               </tns:programId>
               <tns:status>
                  <xsl:value-of select="ns1:status"/>
               </tns:status>
            </tns:loyaltyPrograms>
         </xsl:for-each>
         <tns:links>
            <tns:rel>
               <xsl:value-of select="$profile/ns1:Root-Element/ns1:links/ns1:rel"/>
            </tns:rel>
            <tns:href>
               <xsl:value-of select="$profile/ns1:Root-Element/ns1:links/ns1:href"/>
            </tns:href>
         </tns:links>
         <tns:id>
            <xsl:value-of select="/ns0:Root-Element/ns0:id"/>
         </tns:id>
         <tns:email>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:email"/>
         </tns:email>
         <tns:derivedSalePriceList>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:derivedSalePriceList"/>
         </tns:derivedSalePriceList>
         <tns:daytimeTelephoneNumber>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:daytimeTelephoneNumber"/>
         </tns:daytimeTelephoneNumber>
         <tns:taxExempt>
            <xsl:value-of select="/ns0:Root-Element/ns0:taxExempt"/>
         </tns:taxExempt>
         <tns:receiveEmail>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:receiveEmail"/>
         </tns:receiveEmail>
         <tns:priceListGroup>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:priceListGroup"/>
         </tns:priceListGroup>
         <tns:active>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:active"/>
         </tns:active>
         <tns:dateOfBirth>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:dateOfBirth"/>
         </tns:dateOfBirth>
         <tns:firstName>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:firstName"/>
         </tns:firstName>
         <tns:repositoryId>
            <xsl:value-of select="/ns0:Root-Element/ns0:id"/>
         </tns:repositoryId>
         <tns:shippingAddress>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:shippingAddress"/>
         </tns:shippingAddress>
         <tns:billingAddress>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:billingAddress"/>
         </tns:billingAddress>
         <tns:userType>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:userType"/>
         </tns:userType>
         <tns:taxPriceInfo>
            <tns:discounted>
               <xsl:value-of select="/ns0:Root-Element/ns0:taxPriceInfo/ns0:discounted"/>
            </tns:discounted>
            <tns:cityTax>
               <xsl:value-of select="/ns0:Root-Element/ns0:taxPriceInfo/ns0:cityTax"/>
            </tns:cityTax>
            <tns:amount>
               <xsl:value-of select="/ns0:Root-Element/ns0:taxPriceInfo/ns0:amount"/>
            </tns:amount>
            <tns:countyTax>
               <xsl:value-of select="/ns0:Root-Element/ns0:taxPriceInfo/ns0:countyTax"/>
            </tns:countyTax>
            <tns:amountIsFinal>
               <xsl:value-of select="/ns0:Root-Element/ns0:taxPriceInfo/ns0:amountIsFinal"/>
            </tns:amountIsFinal>
            <tns:districtTax>
               <xsl:value-of select="/ns0:Root-Element/ns0:taxPriceInfo/ns0:districtTax"/>
            </tns:districtTax>
            <tns:stateTax>
               <xsl:value-of select="/ns0:Root-Element/ns0:taxPriceInfo/ns0:stateTax"/>
            </tns:stateTax>
            <tns:currencyCode>
               <xsl:value-of select="/ns0:Root-Element/ns0:taxPriceInfo/ns0:currencyCode"/>
            </tns:currencyCode>
            <tns:countryTax>
               <xsl:value-of select="/ns0:Root-Element/ns0:taxPriceInfo/ns0:countryTax"/>
            </tns:countryTax>
         </tns:taxPriceInfo>
         <tns:shippingGroups>
            <tns:shippingMethod>
               <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingMethod"/>
            </tns:shippingMethod>
            <tns:description>
               <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:description"/>
            </tns:description>
            <tns:submittedDate>
               <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:submittedDate"/>
            </tns:submittedDate>
            <tns:priceInfo>
               <tns:discounted>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:priceInfo/ns0:discounted"/>
               </tns:discounted>
               <tns:amount>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:priceInfo/ns0:amount"/>
               </tns:amount>
               <tns:rawShipping>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:priceInfo/ns0:rawShipping"/>
               </tns:rawShipping>
               <tns:amountIsFinal>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:priceInfo/ns0:amountIsFinal"/>
               </tns:amountIsFinal>
               <tns:currencyCode>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:priceInfo/ns0:currencyCode"/>
               </tns:currencyCode>
            </tns:priceInfo>
            <tns:shipOnDate>
               <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shipOnDate"/>
            </tns:shipOnDate>
            <tns:actualShipDate>
               <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:actualShipDate"/>
            </tns:actualShipDate>
            <tns:trackingInfo>
               <tns:carrierName>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:trackingInfo/ns0:carrierName"/>
               </tns:carrierName>
               <tns:trackingUrl>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:trackingInfo/ns0:trackingUrl"/>
               </tns:trackingUrl>
               <tns:carrierId>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:trackingInfo/ns0:carrierId"/>
               </tns:carrierId>
               <tns:trackingNumber>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:trackingInfo/ns0:trackingNumber"/>
               </tns:trackingNumber>
            </tns:trackingInfo>
            <tns:specialInstructions>
               <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:specialInstructions"/>
            </tns:specialInstructions>
            <tns:shippingAddress>
               <tns:lastName>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:lastName"/>
               </tns:lastName>
               <tns:country>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:country"/>
               </tns:country>
               <tns:address3>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:address3"/>
               </tns:address3>
               <tns:city>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:city"/>
               </tns:city>
               <tns:address2>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:address2"/>
               </tns:address2>
               <tns:prefix>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:prefix"/>
               </tns:prefix>
               <tns:address1>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:address1"/>
               </tns:address1>
               <tns:companyName>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:companyName"/>
               </tns:companyName>
               <tns:jobTitle>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:jobTitle"/>
               </tns:jobTitle>
               <tns:postalCode>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:postalCode"/>
               </tns:postalCode>
               <tns:county>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:county"/>
               </tns:county>
               <tns:suffix>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:suffix"/>
               </tns:suffix>
               <tns:ownerId>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:ownerId"/>
               </tns:ownerId>
               <tns:firstName>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:firstName"/>
               </tns:firstName>
               <tns:phoneNumber>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:phoneNumber"/>
               </tns:phoneNumber>
               <tns:faxNumber>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:faxNumber"/>
               </tns:faxNumber>
               <tns:middleName>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:middleName"/>
               </tns:middleName>
               <tns:state>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:state"/>
               </tns:state>
               <tns:id>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:id"/>
               </tns:id>
               <tns:email>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingAddress/ns0:email"/>
               </tns:email>
            </tns:shippingAddress>
            <tns:commerceItemRelationships>
               <tns:commerceItemId>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:commerceItemRelationships/ns0:commerceItemId"/>
               </tns:commerceItemId>
               <tns:amount>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:commerceItemRelationships/ns0:amount"/>
               </tns:amount>
               <tns:quantity>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:commerceItemRelationships/ns0:quantity"/>
               </tns:quantity>
               <tns:relationshipType>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:commerceItemRelationships/ns0:relationshipType"/>
               </tns:relationshipType>
               <tns:returnedQuantity>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:commerceItemRelationships/ns0:returnedQuantity"/>
               </tns:returnedQuantity>
               <tns:id>
                  <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:commerceItemRelationships/ns0:id"/>
               </tns:id>
            </tns:commerceItemRelationships>
            <tns:state>
               <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:state"/>
            </tns:state>
            <tns:id>
               <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:id"/>
            </tns:id>
            <tns:stateDetail>
               <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:stateDetail"/>
            </tns:stateDetail>
            <tns:trackingNumber>
               <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:trackingNumber"/>
            </tns:trackingNumber>
            <tns:shippingGroupClassType>
               <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingGroupClassType"/>
            </tns:shippingGroupClassType>
         </tns:shippingGroups>
         <tns:priceGroupId>
            <xsl:value-of select="/ns0:Root-Element/ns0:priceGroupId"/>
         </tns:priceGroupId>
         <tns:lastModifiedTime>
            <xsl:value-of select="/ns0:Root-Element/ns0:lastModifiedTime"/>
         </tns:lastModifiedTime>
         <tns:creationTime>
            <xsl:value-of select="/ns0:Root-Element/ns0:creationTime"/>
         </tns:creationTime>
         <tns:sourceSystem>
            <xsl:value-of select="/ns0:Root-Element/ns0:sourceSystem"/>
         </tns:sourceSystem>
         <tns:profile>
            <tns:lastName>
               <xsl:value-of select="/ns0:Root-Element/ns0:profile/ns0:lastName"/>
            </tns:lastName>
            <tns:firstName>
               <xsl:value-of select="/ns0:Root-Element/ns0:profile/ns0:firstName"/>
            </tns:firstName>
            <tns:shippingAddress>
               <tns:country>
                  <xsl:value-of select="/ns0:Root-Element/ns0:profile/ns0:shippingAddress/ns0:country"/>
               </tns:country>
               <tns:phoneNumber>
                  <xsl:value-of select="/ns0:Root-Element/ns0:profile/ns0:shippingAddress/ns0:phoneNumber"/>
               </tns:phoneNumber>
               <tns:address3>
                  <xsl:value-of select="/ns0:Root-Element/ns0:profile/ns0:shippingAddress/ns0:address3"/>
               </tns:address3>
               <tns:address2>
                  <xsl:value-of select="/ns0:Root-Element/ns0:profile/ns0:shippingAddress/ns0:address2"/>
               </tns:address2>
               <tns:city>
                  <xsl:value-of select="/ns0:Root-Element/ns0:profile/ns0:shippingAddress/ns0:city"/>
               </tns:city>
               <tns:address1>
                  <xsl:value-of select="/ns0:Root-Element/ns0:profile/ns0:shippingAddress/ns0:address1"/>
               </tns:address1>
               <tns:postalCode>
                  <xsl:value-of select="/ns0:Root-Element/ns0:profile/ns0:shippingAddress/ns0:postalCode"/>
               </tns:postalCode>
               <tns:county>
                  <xsl:value-of select="/ns0:Root-Element/ns0:profile/ns0:shippingAddress/ns0:county"/>
               </tns:county>
               <tns:state>
                  <xsl:value-of select="/ns0:Root-Element/ns0:profile/ns0:shippingAddress/ns0:state"/>
               </tns:state>
            </tns:shippingAddress>
            <tns:middleName>
               <xsl:value-of select="/ns0:Root-Element/ns0:profile/ns0:middleName"/>
            </tns:middleName>
            <tns:email>
               <xsl:value-of select="/ns0:Root-Element/ns0:profile/ns0:email"/>
            </tns:email>
         </tns:profile>
         <tns:salesChannel>
            <xsl:value-of select="/ns0:Root-Element/ns0:salesChannel"/>
         </tns:salesChannel>
         <tns:shippingGroupCount>
            <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroupCount"/>
         </tns:shippingGroupCount>
         <tns:paymentGroups>
            <tns:PONumber>
               <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:PONumber"/>
            </tns:PONumber>
            <tns:expirationYear>
               <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:expirationYear"/>
            </tns:expirationYear>
            <tns:amountAuthorized>
               <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:amountAuthorized"/>
            </tns:amountAuthorized>
            <tns:amount>
               <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:amount"/>
            </tns:amount>
            <tns:expirationMonth>
               <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:expirationMonth"/>
            </tns:expirationMonth>
            <tns:submittedDate>
               <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:submittedDate"/>
            </tns:submittedDate>
            <tns:authorizationStatus>
               <tns:transactionUuid>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:authorizationStatus/ns0:transactionUuid"/>
               </tns:transactionUuid>
               <tns:authorizationDecision>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:authorizationStatus/ns0:authorizationDecision"/>
               </tns:authorizationDecision>
               <tns:amount>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:authorizationStatus/ns0:amount"/>
               </tns:amount>
               <tns:transactionSuccess>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:authorizationStatus/ns0:transactionSuccess"/>
               </tns:transactionSuccess>
               <tns:errorMessage>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:authorizationStatus/ns0:errorMessage"/>
               </tns:errorMessage>
               <tns:currency>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:authorizationStatus/ns0:currency"/>
               </tns:currency>
               <tns:reasonCode>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:authorizationStatus/ns0:reasonCode"/>
               </tns:reasonCode>
               <tns:transactionId>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:authorizationStatus/ns0:transactionId"/>
               </tns:transactionId>
            </tns:authorizationStatus>
            <tns:token>
               <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:token"/>
            </tns:token>
            <tns:paymentGroupClassType>
               <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:paymentGroupClassType"/>
            </tns:paymentGroupClassType>
            <tns:creditCardNumber>
               <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:creditCardNumber"/>
            </tns:creditCardNumber>
            <tns:paymentMethod>
               <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:paymentMethod"/>
            </tns:paymentMethod>
            <tns:billingAddress>
               <tns:lastName>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:lastName"/>
               </tns:lastName>
               <tns:country>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:country"/>
               </tns:country>
               <tns:address3>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:address3"/>
               </tns:address3>
               <tns:city>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:city"/>
               </tns:city>
               <tns:address2>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:address2"/>
               </tns:address2>
               <tns:prefix>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:prefix"/>
               </tns:prefix>
               <tns:address1>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:address1"/>
               </tns:address1>
               <tns:companyName>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:companyName"/>
               </tns:companyName>
               <tns:jobTitle>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:jobTitle"/>
               </tns:jobTitle>
               <tns:postalCode>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:postalCode"/>
               </tns:postalCode>
               <tns:county>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:county"/>
               </tns:county>
               <tns:suffix>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:suffix"/>
               </tns:suffix>
               <tns:ownerId>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:ownerId"/>
               </tns:ownerId>
               <tns:firstName>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:firstName"/>
               </tns:firstName>
               <tns:phoneNumber>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:phoneNumber"/>
               </tns:phoneNumber>
               <tns:faxNumber>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:faxNumber"/>
               </tns:faxNumber>
               <tns:middleName>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:middleName"/>
               </tns:middleName>
               <tns:state>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:state"/>
               </tns:state>
               <tns:id>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:id"/>
               </tns:id>
               <tns:email>
                  <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:billingAddress/ns0:email"/>
               </tns:email>
            </tns:billingAddress>
            <tns:id>
               <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:id"/>
            </tns:id>
            <tns:currencyCode>
               <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroups/ns0:currencyCode"/>
            </tns:currencyCode>
         </tns:paymentGroups>
         <tns:paymentGroupCount>
            <xsl:value-of select="/ns0:Root-Element/ns0:paymentGroupCount"/>
         </tns:paymentGroupCount>
         <tns:organizationId>
            <xsl:value-of select="/ns0:Root-Element/ns0:organizationId"/>
         </tns:organizationId>
         <tns:relationships>
            <tns:paymentGroupId>
               <xsl:value-of select="/ns0:Root-Element/ns0:relationships/ns0:paymentGroupId"/>
            </tns:paymentGroupId>
            <tns:amount>
               <xsl:value-of select="/ns0:Root-Element/ns0:relationships/ns0:amount"/>
            </tns:amount>
            <tns:relationshipType>
               <xsl:value-of select="/ns0:Root-Element/ns0:relationships/ns0:relationshipType"/>
            </tns:relationshipType>
            <tns:id>
               <xsl:value-of select="/ns0:Root-Element/ns0:relationships/ns0:id"/>
            </tns:id>
         </tns:relationships>
         <tns:priceInfo>
            <tns:discounted>
               <xsl:value-of select="/ns0:Root-Element/ns0:priceInfo/ns0:discounted"/>
            </tns:discounted>
            <tns:amount>
               <xsl:value-of select="/ns0:Root-Element/ns0:priceInfo/ns0:amount"/>
            </tns:amount>
            <tns:total>
               <xsl:value-of select="/ns0:Root-Element/ns0:priceInfo/ns0:total"/>
            </tns:total>
            <tns:shipping>
               <xsl:value-of select="/ns0:Root-Element/ns0:priceInfo/ns0:shipping"/>
            </tns:shipping>
            <tns:manualAdjustmentTotal>
               <xsl:value-of select="/ns0:Root-Element/ns0:priceInfo/ns0:manualAdjustmentTotal"/>
            </tns:manualAdjustmentTotal>
            <tns:amountIsFinal>
               <xsl:value-of select="/ns0:Root-Element/ns0:priceInfo/ns0:amountIsFinal"/>
            </tns:amountIsFinal>
            <tns:discountAmount>
               <xsl:value-of select="/ns0:Root-Element/ns0:priceInfo/ns0:discountAmount"/>
            </tns:discountAmount>
            <tns:tax>
               <xsl:value-of select="/ns0:Root-Element/ns0:priceInfo/ns0:tax"/>
            </tns:tax>
            <tns:rawSubtotal>
               <xsl:value-of select="/ns0:Root-Element/ns0:priceInfo/ns0:rawSubtotal"/>
            </tns:rawSubtotal>
            <tns:currencyCode>
               <xsl:value-of select="/ns0:Root-Element/ns0:priceInfo/ns0:currencyCode"/>
            </tns:currencyCode>
         </tns:priceInfo>
         <tns:recurringChargePriceInfo>
            <tns:discounted>
               <xsl:value-of select="/ns0:Root-Element/ns0:recurringChargePriceInfo/ns0:discounted"/>
            </tns:discounted>
            <tns:amount>
               <xsl:value-of select="/ns0:Root-Element/ns0:recurringChargePriceInfo/ns0:amount"/>
            </tns:amount>
            <tns:total>
               <xsl:value-of select="/ns0:Root-Element/ns0:recurringChargePriceInfo/ns0:total"/>
            </tns:total>
            <tns:shipping>
               <xsl:value-of select="/ns0:Root-Element/ns0:recurringChargePriceInfo/ns0:shipping"/>
            </tns:shipping>
            <tns:subTotalByFrequency>
               <tns:amount>
                  <xsl:value-of select="/ns0:Root-Element/ns0:recurringChargePriceInfo/ns0:subTotalByFrequency/ns0:amount"/>
               </tns:amount>
               <tns:frequency>
                  <xsl:value-of select="/ns0:Root-Element/ns0:recurringChargePriceInfo/ns0:subTotalByFrequency/ns0:frequency"/>
               </tns:frequency>
            </tns:subTotalByFrequency>
            <tns:taxByFrequency>
               <tns:amount>
                  <xsl:value-of select="/ns0:Root-Element/ns0:recurringChargePriceInfo/ns0:taxByFrequency/ns0:amount"/>
               </tns:amount>
               <tns:frequency>
                  <xsl:value-of select="/ns0:Root-Element/ns0:recurringChargePriceInfo/ns0:taxByFrequency/ns0:frequency"/>
               </tns:frequency>
            </tns:taxByFrequency>
            <tns:manualAdjustmentTotal>
               <xsl:value-of select="/ns0:Root-Element/ns0:recurringChargePriceInfo/ns0:manualAdjustmentTotal"/>
            </tns:manualAdjustmentTotal>
            <tns:amountIsFinal>
               <xsl:value-of select="/ns0:Root-Element/ns0:recurringChargePriceInfo/ns0:amountIsFinal"/>
            </tns:amountIsFinal>
            <tns:discountAmount>
               <xsl:value-of select="/ns0:Root-Element/ns0:recurringChargePriceInfo/ns0:discountAmount"/>
            </tns:discountAmount>
            <tns:tax>
               <xsl:value-of select="/ns0:Root-Element/ns0:recurringChargePriceInfo/ns0:tax"/>
            </tns:tax>
            <tns:rawSubtotal>
               <xsl:value-of select="/ns0:Root-Element/ns0:recurringChargePriceInfo/ns0:rawSubtotal"/>
            </tns:rawSubtotal>
            <tns:currencyCode>
               <xsl:value-of select="/ns0:Root-Element/ns0:recurringChargePriceInfo/ns0:currencyCode"/>
            </tns:currencyCode>
         </tns:recurringChargePriceInfo>
         <tns:profileId>
            <xsl:value-of select="/ns0:Root-Element/ns0:profileId"/>
         </tns:profileId>
         <tns:siteId>
            <xsl:value-of select="/ns0:Root-Element/ns0:siteId"/>
         </tns:siteId>
         <tns:totalCommerceItemCount>
            <xsl:value-of select="/ns0:Root-Element/ns0:totalCommerceItemCount"/>
         </tns:totalCommerceItemCount>
         <tns:state>
            <xsl:value-of select="/ns0:Root-Element/ns0:state"/>
         </tns:state>
         <tns:commerceItems>
            <tns:deactivationDate>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:deactivationDate"/>
            </tns:deactivationDate>
            <tns:returnedQuantity>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:returnedQuantity"/>
            </tns:returnedQuantity>
            <tns:availabilityDate>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:availabilityDate"/>
            </tns:availabilityDate>
            <tns:billingAccountId>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:billingAccountId"/>
            </tns:billingAccountId>
            <tns:preOrderQuantity>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:preOrderQuantity"/>
            </tns:preOrderQuantity>
            <tns:configuratorId>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:configuratorId"/>
            </tns:configuratorId>
            <tns:priceInfo>
               <tns:discounted>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:discounted"/>
               </tns:discounted>
               <tns:amount>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:amount"/>
               </tns:amount>
               <tns:rawTotalPrice>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:rawTotalPrice"/>
               </tns:rawTotalPrice>
               <tns:salePrice>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:salePrice"/>
               </tns:salePrice>
               <tns:priceListId>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:priceListId"/>
               </tns:priceListId>
               <tns:quantityDiscounted>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:quantityDiscounted"/>
               </tns:quantityDiscounted>
               <tns:amountIsFinal>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:amountIsFinal"/>
               </tns:amountIsFinal>
               <tns:onSale>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:onSale"/>
               </tns:onSale>
               <tns:shippingSurcharge>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:shippingSurcharge"/>
               </tns:shippingSurcharge>
               <tns:discountable>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:discountable"/>
               </tns:discountable>
               <tns:currencyCode>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:currencyCode"/>
               </tns:currencyCode>
               <tns:currentPriceDetailsSorted>
                  <tns:discounted>
                     <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:currentPriceDetailsSorted/ns0:discounted"/>
                  </tns:discounted>
                  <tns:amount>
                     <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:currentPriceDetailsSorted/ns0:amount"/>
                  </tns:amount>
                  <tns:quantity>
                     <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:currentPriceDetailsSorted/ns0:quantity"/>
                  </tns:quantity>
                  <tns:amountIsFinal>
                     <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:currentPriceDetailsSorted/ns0:amountIsFinal"/>
                  </tns:amountIsFinal>
                  <tns:range>
                     <tns:lowBound>
                        <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:currentPriceDetailsSorted/ns0:range/ns0:lowBound"/>
                     </tns:lowBound>
                     <tns:highBound>
                        <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:currentPriceDetailsSorted/ns0:range/ns0:highBound"/>
                     </tns:highBound>
                     <tns:size>
                        <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:currentPriceDetailsSorted/ns0:range/ns0:size"/>
                     </tns:size>
                  </tns:range>
                  <tns:tax>
                     <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:currentPriceDetailsSorted/ns0:tax"/>
                  </tns:tax>
                  <tns:detailedUnitPrice>
                     <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:currentPriceDetailsSorted/ns0:detailedUnitPrice"/>
                  </tns:detailedUnitPrice>
                  <tns:currencyCode>
                     <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:currentPriceDetailsSorted/ns0:currencyCode"/>
                  </tns:currencyCode>
               </tns:currentPriceDetailsSorted>
               <tns:listPrice>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:priceInfo/ns0:listPrice"/>
               </tns:listPrice>
            </tns:priceInfo>
            <tns:assetId>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:assetId"/>
            </tns:assetId>
            <tns:externalRecurringChargeDetails>
               <tns:externalRecurringCharge>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:externalRecurringChargeDetails/ns0:externalRecurringCharge"/>
               </tns:externalRecurringCharge>
               <tns:externalRecurringChargeFrequency>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:externalRecurringChargeDetails/ns0:externalRecurringChargeFrequency"/>
               </tns:externalRecurringChargeFrequency>
               <tns:externalRecurringChargeDuration>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:externalRecurringChargeDetails/ns0:externalRecurringChargeDuration"/>
               </tns:externalRecurringChargeDuration>
            </tns:externalRecurringChargeDetails>
            <tns:externalPriceDetails>
               <tns:externalPriceQuantity>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:externalPriceDetails/ns0:externalPriceQuantity"/>
               </tns:externalPriceQuantity>
               <tns:externalPrice>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:externalPriceDetails/ns0:externalPrice"/>
               </tns:externalPrice>
            </tns:externalPriceDetails>
            <tns:actionCode>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:actionCode"/>
            </tns:actionCode>
            <tns:id>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:id"/>
            </tns:id>
            <tns:serviceId>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:serviceId"/>
            </tns:serviceId>
            <xsl:for-each select="/ns0:Root-Element/ns0:commerceItems/ns0:commerceItems">
               <tns:commerceItems>
                  <tns:serviceAccountId>
                     <xsl:value-of select="ns0:serviceAccountId"/>
                  </tns:serviceAccountId>
                  <tns:deactivationDate>
                     <xsl:value-of select="ns0:deactivationDate"/>
                  </tns:deactivationDate>
                  <tns:quantity>
                     <xsl:value-of select="ns0:quantity"/>
                  </tns:quantity>
                  <tns:productId>
                     <xsl:value-of select="ns0:productId"/>
                  </tns:productId>
                  <tns:billingAccountId>
                     <xsl:value-of select="ns0:billingAccountId"/>
                  </tns:billingAccountId>
                  <tns:catalogRefId>
                     <xsl:value-of select="ns0:catalogRefId"/>
                  </tns:catalogRefId>
                  <tns:customerAccountId>
                     <xsl:value-of select="ns0:customerAccountId"/>
                  </tns:customerAccountId>
                  <xsl:if test="ns0:recurringChargePriceInfo">
                     <tns:recurringChargePriceInfo>
                        <tns:discounted>
                           <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:discounted"/>
                        </tns:discounted>
                        <tns:amount>
                           <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:amount"/>
                        </tns:amount>
                        <tns:rawTotalPrice>
                           <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:rawTotalPrice"/>
                        </tns:rawTotalPrice>
                        <tns:salePrice>
                           <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:salePrice"/>
                        </tns:salePrice>
                        <tns:priceListId>
                           <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:priceListId"/>
                        </tns:priceListId>
                        <tns:quantityDiscounted>
                           <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:quantityDiscounted"/>
                        </tns:quantityDiscounted>
                        <tns:amountIsFinal>
                           <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:amountIsFinal"/>
                        </tns:amountIsFinal>
                        <tns:onSale>
                           <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:onSale"/>
                        </tns:onSale>
                        <tns:shippingSurcharge>
                           <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:shippingSurcharge"/>
                        </tns:shippingSurcharge>
                        <tns:discountable>
                           <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:discountable"/>
                        </tns:discountable>
                        <tns:currentPriceDetailsSorted>
                           <tns:discounted>
                              <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:discounted"/>
                           </tns:discounted>
                           <tns:amount>
                              <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:amount"/>
                           </tns:amount>
                           <tns:quantity>
                              <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:quantity"/>
                           </tns:quantity>
                           <tns:amountIsFinal>
                              <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:amountIsFinal"/>
                           </tns:amountIsFinal>
                           <tns:range>
                              <tns:lowBound>
                                 <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:range/ns0:lowBound"/>
                              </tns:lowBound>
                              <tns:highBound>
                                 <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:range/ns0:highBound"/>
                              </tns:highBound>
                              <tns:size>
                                 <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:range/ns0:size"/>
                              </tns:size>
                           </tns:range>
                           <tns:tax>
                              <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:tax"/>
                           </tns:tax>
                           <tns:orderDiscountShare>
                              <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:orderDiscountShare"/>
                           </tns:orderDiscountShare>
                           <tns:detailedUnitPrice>
                              <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:detailedUnitPrice"/>
                           </tns:detailedUnitPrice>
                           <tns:currencyCode>
                              <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:currencyCode"/>
                           </tns:currencyCode>
                        </tns:currentPriceDetailsSorted>
                        <tns:currencyCode>
                           <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:currencyCode"/>
                        </tns:currencyCode>
                        <tns:listPrice>
                           <xsl:value-of select="ns0:recurringChargePriceInfo/ns0:listPrice"/>
                        </tns:listPrice>
                     </tns:recurringChargePriceInfo>
                  </xsl:if>
                  <tns:assetId>
                     <xsl:value-of select="ns0:assetId"/>
                  </tns:assetId>
                  <xsl:if test="ns0:externalRecurringChargeDetails">
                     <tns:externalRecurringChargeDetails>
                        <tns:externalRecurringCharge>
                           <xsl:value-of select="ns0:externalRecurringChargeDetails/ns0:externalRecurringCharge"/>
                        </tns:externalRecurringCharge>
                        <tns:externalRecurringChargeFrequency>
                           <xsl:value-of select="ns0:externalRecurringChargeDetails/ns0:externalRecurringChargeFrequency"/>
                        </tns:externalRecurringChargeFrequency>
                        <tns:externalRecurringChargeDuration>
                           <xsl:value-of select="ns0:externalRecurringChargeDetails/ns0:externalRecurringChargeDuration"/>
                        </tns:externalRecurringChargeDuration>
                     </tns:externalRecurringChargeDetails>
                  </xsl:if>
                  <tns:actionCode>
                     <xsl:value-of select="ns0:actionCode"/>
                  </tns:actionCode>
                  <tns:activationDate>
                     <xsl:value-of select="ns0:activationDate"/>
                  </tns:activationDate>
                  <tns:serviceId>
                     <xsl:value-of select="ns0:serviceId"/>
                  </tns:serviceId>
               </tns:commerceItems>
            </xsl:for-each>
            <tns:serviceAccountId>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:serviceAccountId"/>
            </tns:serviceAccountId>
            <tns:quantity>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:quantity"/>
            </tns:quantity>
            <tns:productId>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:productId"/>
            </tns:productId>
            <tns:externalId>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:externalId"/>
            </tns:externalId>
            <tns:catalogRefId>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:catalogRefId"/>
            </tns:catalogRefId>
            <tns:customerAccountId>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:customerAccountId"/>
            </tns:customerAccountId>
            <tns:recurringChargePriceInfo>
               <tns:discounted>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:discounted"/>
               </tns:discounted>
               <tns:amount>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:amount"/>
               </tns:amount>
               <tns:rawTotalPrice>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:rawTotalPrice"/>
               </tns:rawTotalPrice>
               <tns:salePrice>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:salePrice"/>
               </tns:salePrice>
               <tns:priceListId>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:priceListId"/>
               </tns:priceListId>
               <tns:quantityDiscounted>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:quantityDiscounted"/>
               </tns:quantityDiscounted>
               <tns:amountIsFinal>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:amountIsFinal"/>
               </tns:amountIsFinal>
               <tns:onSale>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:onSale"/>
               </tns:onSale>
               <tns:shippingSurcharge>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:shippingSurcharge"/>
               </tns:shippingSurcharge>
               <tns:discountable>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:discountable"/>
               </tns:discountable>
               <tns:currentPriceDetailsSorted>
                  <tns:discounted>
                     <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:discounted"/>
                  </tns:discounted>
                  <tns:amount>
                     <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:amount"/>
                  </tns:amount>
                  <tns:quantity>
                     <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:quantity"/>
                  </tns:quantity>
                  <tns:amountIsFinal>
                     <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:amountIsFinal"/>
                  </tns:amountIsFinal>
                  <tns:range>
                     <tns:lowBound>
                        <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:range/ns0:lowBound"/>
                     </tns:lowBound>
                     <tns:highBound>
                        <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:range/ns0:highBound"/>
                     </tns:highBound>
                     <tns:size>
                        <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:range/ns0:size"/>
                     </tns:size>
                  </tns:range>
                  <tns:tax>
                     <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:tax"/>
                  </tns:tax>
                  <tns:orderDiscountShare>
                     <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:orderDiscountShare"/>
                  </tns:orderDiscountShare>
                  <tns:detailedUnitPrice>
                     <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:detailedUnitPrice"/>
                  </tns:detailedUnitPrice>
                  <tns:currencyCode>
                     <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:currentPriceDetailsSorted/ns0:currencyCode"/>
                  </tns:currencyCode>
               </tns:currentPriceDetailsSorted>
               <tns:currencyCode>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:currencyCode"/>
               </tns:currencyCode>
               <tns:listPrice>
                  <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:recurringChargePriceInfo/ns0:listPrice"/>
               </tns:listPrice>
            </tns:recurringChargePriceInfo>
            <tns:productDisplayName>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:productDisplayName"/>
            </tns:productDisplayName>
            <tns:activationDate>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:activationDate"/>
            </tns:activationDate>
            <tns:backOrderQuantity>
               <xsl:value-of select="/ns0:Root-Element/ns0:commerceItems/ns0:backOrderQuantity"/>
            </tns:backOrderQuantity>
         </tns:commerceItems>
      </tns:Root-Element>
   </xsl:template>
</xsl:stylesheet>
