<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:ns1="http://TargetNamespace.com/OCCGetProfileOrder_profileRequest_response"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:tns="http://TargetNamespace.com/GetEnrichOrderProfile_OrderProfileOCC_response"
                xmlns:ns0="http://TargetNamespace.com/OCCGetProfileOrder_orderRequest_response"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns1 ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../resources/nxsd_OrderRes.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element"
                                           namespace="http://TargetNamespace.com/OCCGetProfileOrder_orderRequest_response"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../resources/nxsd_ProfileRes.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element"
                                           namespace="http://TargetNamespace.com/OCCGetProfileOrder_profileRequest_response"/>
            <oracle-xsl-mapper:param name="profile"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../resources/nxsd_OrderProfileOCCRes.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element"
                                           namespace="http://TargetNamespace.com/GetEnrichOrderProfile_OrderProfileOCC_response"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI MAR 09 10:25:04 BRT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="profile"/>
   <xsl:template match="/">
      <tns:Root-Element>
         <tns:gender>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:gender"/>
         </tns:gender>
         <tns:CPF>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:CPF"/>
         </tns:CPF>
         <tns:firstVisitDate>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:firstVisitDate"/>
         </tns:firstVisitDate>
         <tns:dateOfBirth>
            <xsl:value-of select="$profile/ns1:Root-Element/ns1:dateOfBirth"/>
         </tns:dateOfBirth>
         <tns:shippingGroups>
            <tns:shippingMethod>
               <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:shippingMethod"/>
            </tns:shippingMethod>
            <tns:description>
               <xsl:value-of select="/ns0:Root-Element/ns0:shippingGroups/ns0:description"/>
            </tns:description>
         </tns:shippingGroups>
         <xsl:for-each select="/ns0:Root-Element/ns0:commerceItems">
            <tns:commerceItems>
               <tns:priceInfo>
                  <tns:amount>
                     <xsl:value-of select="ns0:priceInfo/ns0:amount"/>
                  </tns:amount>
                  <tns:currencyCode>
                     <xsl:value-of select="ns0:priceInfo/ns0:currencyCode"/>
                  </tns:currencyCode>
               </tns:priceInfo>
               <tns:id>
                  <xsl:value-of select="ns0:id"/>
               </tns:id>
               <tns:quantity>
                  <xsl:value-of select="ns0:quantity"/>
               </tns:quantity>
               <tns:productId>
                  <xsl:value-of select="ns0:productId"/>
               </tns:productId>
               <tns:catalogRefId>
                  <xsl:value-of select="ns0:catalogRefId"/>
               </tns:catalogRefId>
               <tns:productDisplayName>
                  <xsl:value-of select="ns0:productDisplayName"/>
               </tns:productDisplayName>
            </tns:commerceItems>
         </xsl:for-each>
      </tns:Root-Element>
   </xsl:template>
</xsl:stylesheet>
