<wsdl:definitions name="WebhookOrderSubmitPS" targetNamespace="http://xmlns.oracle.com/SBAplPassarela/PASSSBWebhookOrderSubmit/WebhookOrderSubmitPS" xmlns:tns="http://xmlns.oracle.com/SBAplPassarela/PASSSBWebhookOrderSubmit/WebhookOrderSubmitPS" xmlns:inp1="http://TargetNamespace.com/WebhookOrderSubmitPS_submit_order_request" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:inp2="http://TargetNamespace.com/WebhookOrderSubmitPS_submit_order_response">
    <plnk:partnerLinkType name="WebhookOrderSubmitPS">
        <plnk:role name="WebhookOrderSubmitPSProvider" portType="tns:WebhookOrderSubmitPS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://TargetNamespace.com/WebhookOrderSubmitPS_submit_order_request" schemaLocation="nxsd_submitOrderReq.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://TargetNamespace.com/WebhookOrderSubmitPS_submit_order_response" schemaLocation="nxsd_submitOrderRes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="submit_order_inputMessage">
        <wsdl:part name="request" element="inp1:Root-Element"/>
    </wsdl:message>
    <wsdl:message name="submit_order_outputMessage">
        <wsdl:part name="reply" element="inp2:Root-Element"/>
    </wsdl:message>
    <wsdl:message name="Rest_EmptyMessage"/>
    <wsdl:portType name="WebhookOrderSubmitPS_ptt">
        <wsdl:operation name="submit_order">
            <wsdl:input message="tns:submit_order_inputMessage"/>
            <wsdl:output message="tns:submit_order_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="WebhookOrderSubmitPS_ptt-binding" type="tns:WebhookOrderSubmitPS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="submit_order">
            <soap:operation soapAction="submit_order"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>